# Generated by Django 4.1 on 2022-09-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercancellation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='store.order'),
        ),
    ]
